### PR TITLE
Fixes @Jakimfett's render issues

### PR DESCRIPTION
**Pull request by hilburn**

### CODE REVIEW

**Comment by jakimfett** [comment]
Merged in https://github.com/jakimfett/AlchemyPlusPlus/commit/6d053d34bacccf68dd5ea5ac0846061ab9d079dd

**Comment by hilburn** [comment]
Hmph - stealing my fixes

**Comment by jakimfett** [comment]
I'd already committed some stuff locally that conflicted, and merging became a headache, and I was tired. So sue me. :-P

**Comment by hilburn** [comment]
it's OS code - I don't think I could sue you even if i wanted to

**Pull request closed without merging**
