### PR TITLE
Zombie Potion Update

### PR DESCRIPTION
**Pull request by hilburn**
Currently you can infect yourself with a Fish Oil bottle - shift+right click with no fish in your inventory. Yes I know it's weird but it's just a test

### CODE REVIEW

**Comment by hilburn** [comment]
poke poke @jakimfett

**Comment by way2muchnoise** [comment]
no @hilburn @jakimfett does not like your PR hehehehe

**Comment by hilburn** [comment]
but... zombies Coral!

**Comment by jakimfett** [comment]
Sorry for the delay on this, we spent 2 days at Grandma's place...no internet, no cell service. ::shudders::

**Pull request merged**
