### PR TITLE
fixes potionIds

### PR DESCRIPTION
**Pull request by way2muchnoise**
for real this time I dun goofed

### CODE REVIEW

**Comment by jakimfett** [comment]
Out of curiosity, why are some numbers hardcoded, and some numbers pulled from the potion?

**Comment by way2muchnoise** [comment]
The ones pulled out are the ones that have no real mc potion but will rework when I have more time so that it makes potions for them

**Comment by jakimfett** [comment]
Ah, gotcha.

**Comment by way2muchnoise** [comment]
@jakimfett I need to make a registry that holds those new potions and the references to the existing mc potions

**Pull request merged**
