### PR TITLE
The Infection Begins

### PR DESCRIPTION
**Pull request by hilburn**
wah wah waaaaaaaa!
(Don't turn on hostileAnimals and start a survival game)

### CODE REVIEW

**Comment by jakimfett** [comment]
What could possibly go wrong?

**Comment by UndeadZeratul** [comment]
All I could hear was this:

https://www.youtube.com/watch?v=VDj-cLnHrRQ

**Comment by jakimfett** [comment]
'zactly

**Comment by hilburn** [comment]
On the plus side. There is very little as amusing as watching a zombie get mobbed by 30 chickens which was how I tested it. 
Gonna try to make villagers flee from zombie players as well, with trading disabled and a chance to "turn" them on attack with a bare hand
I was thinking 1 in 10 zombies should be infectious with maybe a 1/3rd chance of infecting per attack

**Comment by jakimfett** [comment]
It should probably be configurable...but for a base infection rate that sounds good.

Couple of things. Make sure that if the player has a regeneration potion effect (I'll make an antidote later...or you could...) they cannot be infected, as I want it to be possible to escape the infection if you're actively diffusing an antidote via the diffuser.

Note that I don't want diffused antidote to instantly cure infections (configurable, perhaps...) ...just keep it from happening. You'll need a slightly stronger dose if you want to get cured.

**Comment by hilburn** [comment]
okie dokie, i'll see what i can do
it's pub quiz night so i'll be coding drunk tonight
expect evilness to occur

**Comment by jakimfett** [comment]
Uh oh. Tremble in your boots, people...hilburn's being evil again.

**Comment by hilburn** [comment]
mwahahahahahahahahahaha

**Pull request merged**
